
use caja_ahorro_bd;


INSERT INTO caja_ahorro_bd.ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Activa', 'La cuenta está activa y en buen estado.');
INSERT INTO caja_ahorro_bd.ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Inactiva', 'La cuenta ha sido desactivada temporalmente.');
INSERT INTO caja_ahorro_bd.ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Pendiente', 'La cuenta está pendiente de aprobación.');
INSERT INTO caja_ahorro_bd.ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Bloqueada', 'La cuenta ha sido bloqueada debido a actividades sospechosas.');
INSERT INTO caja_ahorro_bd.ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Cerrada', 'La cuenta ha sido cerrada permanentemente.');

INSERT INTO caja_ahorro_bd.ESTATUS_PRESTAMOS (NOMBRE, DESCRIPCION) VALUES ('Pendiente', 'El préstamo está pendiente de aprobación.');
INSERT INTO caja_ahorro_bd.ESTATUS_PRESTAMOS (NOMBRE, DESCRIPCION) VALUES ('Aprobado', 'El préstamo ha sido aprobado y está activo.');
INSERT INTO caja_ahorro_bd.ESTATUS_PRESTAMOS (NOMBRE, DESCRIPCION) VALUES ('Rechazado', 'El préstamo ha sido rechazado.');
INSERT INTO caja_ahorro_bd.ESTATUS_PRESTAMOS (NOMBRE, DESCRIPCION) VALUES ('Pagado', 'El préstamo ha sido completamente pagado.');
INSERT INTO caja_ahorro_bd.ESTATUS_PRESTAMOS (NOMBRE, DESCRIPCION) VALUES ('Vencido', 'El préstamo está vencido y pendiente de pago.');

INSERT INTO caja_ahorro_bd.ESTATUS_TRANSACCION (NOMBRE, DESCRIPCION) VALUES ('Exitosa', 'La transacción se ha completado con éxito.');
INSERT INTO caja_ahorro_bd.ESTATUS_TRANSACCION (NOMBRE, DESCRIPCION) VALUES ('Pendiente', 'La transacción está pendiente de procesamiento.');
INSERT INTO caja_ahorro_bd.ESTATUS_TRANSACCION (NOMBRE, DESCRIPCION) VALUES ('Rechazada', 'La transacción ha sido rechazada.');

INSERT INTO caja_ahorro_bd.TIPO_TRANSACCION (NOMBRE, DESCRIPCION) VALUES ('Abono a cuenta', 'Transacción para abonar a cuenta');
INSERT INTO caja_ahorro_bd.TIPO_TRANSACCION (NOMBRE, DESCRIPCION) VALUES ('Pago de prestamo', 'Transaccion para pagar un prestamo');

INSERT INTO caja_ahorro_bd.ROL (NOMBRE, DESCRIPCION) VALUES ('Admin', 'Rol de administrador.');
INSERT INTO caja_ahorro_bd.ROL (NOMBRE, DESCRIPCION) VALUES ('Usuario', 'Usuarios registrados.');
INSERT INTO caja_ahorro_bd.ROL (NOMBRE, DESCRIPCION) VALUES ('Moderador', 'Rol con permisos moderados.');
INSERT INTO caja_ahorro_bd.ROL (NOMBRE, DESCRIPCION) VALUES ('Editor', 'Editar contenido.');
INSERT INTO caja_ahorro_bd.ROL (NOMBRE, DESCRIPCION) VALUES ('Invitado', 'Usuarios no registrados o invitados.');

INSERT INTO caja_ahorro_bd.USUARIO (EMAIL, PASSWORD, APELLIDO_MATERNO, NUMERO_TELEFONICO, NOMBRE, APELLIDO_PATERNO, ROL_ID, fotografia) VALUES ('oswaldo121oswaldo@gmail.com', '$2a$10$ckDE5Xcxv2t2IAdwYRLS6OR805yYRm4UhimrGntKhBtjxtjgcgTEK', 'Pérez', '5586808072', 'Oswaldo', 'Cabrera', 1, '1_5_foto_perfil.jpeg');
INSERT INTO caja_ahorro_bd.USUARIO (EMAIL, PASSWORD, APELLIDO_MATERNO, NUMERO_TELEFONICO, NOMBRE, APELLIDO_PATERNO, ROL_ID, fotografia) VALUES ('sofia@gmail.com', '$2a$10$5nZq4M5QCQl66AH6ugczCeEWo6w8PJi9NGWBKJke/Owu0KillMfJa', 'López', '5515636281', 'Sofía', 'Cabrera', 2, '2_foto-perfil2.jpeg');

INSERT INTO caja_ahorro_bd.CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (10000, '2024-01-15 21:58:02', 1, 1);
INSERT INTO caja_ahorro_bd.CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (200, '2024-01-15 22:02:31', 2, 1);

INSERT INTO caja_ahorro_bd.TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID, comprobante) VALUES (10000, '2024-01-15 22:01:32', 1, 1, 1, 'transferencia.jpeg');
INSERT INTO caja_ahorro_bd.TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID, comprobante) VALUES (108, '2024-01-15 22:04:05', 2, 2, 1, '2_transferencia2.jpeg');
INSERT INTO caja_ahorro_bd.TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID, comprobante) VALUES (200, '2024-01-15 22:05:19', 2, 1, 1, 'transferencia3.jpeg');
INSERT INTO caja_ahorro_bd.TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID, comprobante) VALUES (100, '2024-01-15 22:05:45', 2, 1, 2, 'transferencia4.jpeg');

INSERT INTO caja_ahorro_bd.HISTORICO_ESTATUS_TRANSACCION (FECHA, ESTATUS_TRANSACCION_ID, TRANSACCION_ID) VALUES ('2024-01-15', 2, 1);
INSERT INTO caja_ahorro_bd.HISTORICO_ESTATUS_TRANSACCION (FECHA, ESTATUS_TRANSACCION_ID, TRANSACCION_ID) VALUES ('2024-01-15', 2, 2);
INSERT INTO caja_ahorro_bd.HISTORICO_ESTATUS_TRANSACCION (FECHA, ESTATUS_TRANSACCION_ID, TRANSACCION_ID) VALUES ('2024-01-15', 2, 3);

INSERT INTO caja_ahorro_bd.TRANSACCION_ABONO_AHORRO (DIAS_ATRASO) VALUES (null);
INSERT INTO caja_ahorro_bd.TRANSACCION_ABONO_AHORRO (DIAS_ATRASO) VALUES (null);
INSERT INTO caja_ahorro_bd.TRANSACCION_ABONO_AHORRO (DIAS_ATRASO) VALUES (null);

INSERT INTO caja_ahorro_bd.PRESTAMO (MENSUALIDADES, INTERES, MONTO_PAGAR, MONTO_ORIGINAL, FECHA_PETICION, USUARIO_ID, ESTATUS_PRESTAMOS_ID, CANTIDAD_PAGADA) VALUES (1, 8, 1080, 1000, '2024-01-15 21:59:37', 1, 1, 0);
INSERT INTO caja_ahorro_bd.PRESTAMO (MENSUALIDADES, INTERES, MONTO_PAGAR, MONTO_ORIGINAL, FECHA_PETICION, USUARIO_ID, ESTATUS_PRESTAMOS_ID, CANTIDAD_PAGADA) VALUES (1, 8, 108, 100, '2024-01-15 22:02:54', 2, 4, 108);
INSERT INTO caja_ahorro_bd.PRESTAMO (MENSUALIDADES, INTERES, MONTO_PAGAR, MONTO_ORIGINAL, FECHA_PETICION, USUARIO_ID, ESTATUS_PRESTAMOS_ID, CANTIDAD_PAGADA) VALUES (3, 8, 324, 300, '2024-01-15 22:03:36', 2, 2, 0);
INSERT INTO caja_ahorro_bd.PRESTAMO (MENSUALIDADES, INTERES, MONTO_PAGAR, MONTO_ORIGINAL, FECHA_PETICION, USUARIO_ID, ESTATUS_PRESTAMOS_ID, CANTIDAD_PAGADA) VALUES (2, 8, 216, 200, '2024-01-15 22:04:17', 2, 1, 0);

INSERT INTO caja_ahorro_bd.HISTORICO_ESTATUS_PRESTAMOS (DEUDA, FECHA_ACTUALIZACION, ESTATUS_PRESTAMOS_ID, PRESTAMO_ID) VALUES (108, '2024-01-15 22:04:05', 2, 2);

INSERT INTO caja_ahorro_bd.TRANSACCION_PAGO_PRESTAMO (PRESTAMO_ID) VALUES (2);
