spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/caja_ahorro_bd
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

#ruta de archivos
ejemplo:
  imagen:
    ruta: /Users/oswaldocabreraperez/Documents/ProyectoFinalDiplomado/caja-ahorro/src/main/resources/static/imagen

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
